### ISSUE TITLE
Bug in uncross.py

### ISSUE THREAD

**Issue by tkaria** [capitalk/strategy#1]
INFO:uncross:Rescue order: Order<id = c3abb6ac-6af4-4abc-9b81-66fd2dc104d4, side = 1, price = 1.2777, qty = 1000000>
WARNING:order_manager:Cancel reject: order_id = 2239f0c7-27cd-4f48-ba04-f013910dd2d7, orig_id = c3abb6ac-6af4-4abc-9b81-66fd2dc104d4, reason =2
Traceback (most recent call last):
  File "uncross.py", line 286, in <module>
    strategy.run(md_update_wrapper, place_orders)
  File "/home/timir/capitalk/strategy/python/strategy_loop.py", line 229, in run
    place_orders()
  File "uncross.py", line 285, in place_orders
    args.max_order_qty)
  File "uncross.py", line 253, in outgoing_logic
    manage_active_cross(max_order_lifetime)
  File "uncross.py", line 194, in manage_active_cross
    rescue_expired = time.time() - order.rescue_start_time >= 5
AttributeError: Order instance has no attribute 'rescue_start_time'

**Comment by iskandr** [comment]
This was fixed in my local branch but I never pushed it back to github. If you pull a new version it should work.

**Comment by tkaria** [comment]
## Can we decomssion byah? All changed pushed? 

Verstuurd met mijn BlackBerry van Vodafone

-----Original Message-----
